Makefile: Properly clean up test VM on image preparation
Remove the entire previous overlay instead of just removing the built
package. This ensures that there are no leftovers from previous
interactive debugging sessions. It also avoids

    error: Override already exists for package 'cockpit-ostree*...'

when running `make vm` twice in a row.