test: Explicitly remove ostree-registry container
In some test runs `OstreeOCICase.testBasic` fails on

> Error: name "ostree-registry" is in use: container already exists

This doesn't reproduce locally. These are destructive tests, so the only
plausible explanation is that the container was not actually removed on
`podman stop` despite the `-rm` option. Clean it up more explicitly.